### ISSUE TITLE
Permission to use this project

### ISSUE THREAD

**Issue by AndnixSH** [INF1NUM/APKToolGUI#6]
I have been maintaining [APKToolGUI](https://github.com/AndnixSH/APKToolGUI) and I just have realized that I don't have rights to use it since project doesn't have license. Can I have your permission to continue distribute it? and what license is appropriate for this? Just wanna comply with the law

**Comment by INF1NUM** [comment]
Of course, you can use and distribute this application as open source software.

**Comment by AndnixSH** [comment]
Thanks!
